### ISSUE TITLE
Top bar nav

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/docs#61]
download
get started
commands
docs
team
subscribe
find us
build reference
bill of health

can we remove bill of health, subscribe, & docs 
and perhaps call `build reference` just `build ref` or `sql build ref`

**Comment by niphlod** [comment]
If I'm not mistaken the top bar is "akin" to the one on the site but sure, we can do whatever

**Comment by potatoqualitee** [comment]
yes, thank you. i used to want that but  now i do not 😅

**Comment by niphlod** [comment]
@potatoqualitee  take a look
