### ISSUE TITLE
Issue with Piping Get-DBADatabase to Backup-DBADatabase and using -ReplaceInName

### ISSUE THREAD

**Issue by wgshef** [dataplat/docs#62]
servername is returning an empty string.
Example:
`Get-DBADatabase -SqlInstance MySQLInstance -RecoveryModel Full | Backup-DbaDatabase -Path V:\servername\Backup\dbname\backuptype -FilePath dbname-backuptype-timestamp.bak -ReplaceInName -CompressBackup -Checksum -type Full -OutputScriptOnly | Out-File C:\DBA\BackupDatabasesFullRM.sql`

Getting message:

`SQL Server cannot check if V:\\Backup\<databasename>\Full exists. You can try disabling this check with -IgnoreFileChecks`

When I run this without the Get-DBADatabase being piped to it (and adding -SqlInstance to the command), it works properly.

**Comment by wsmelton** [comment]
We've had a few version releases since this issue was created. If the issue still exists in the latest release please create a new issue on the module's repo [dataplat/dbatools](https://github.com/dataplat/dbatools/issues).
