### ISSUE TITLE
Claudio's name requires unicode and messes up on the website

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/docs#65]
Example: https://docs.dbatools.io/Move-DbaDbFile

**Comment by potatoqualitee** [comment]
HMM! Okay let's see what I can figure out 🤔

**Comment by potatoqualitee** [comment]
sweet! pwsh supports it, let me change the shell used and the UTF8 output

![image](https://user-images.githubusercontent.com/8278033/178962553-4ab48b0f-ea77-4cca-826e-fe5d4db4c1da.png)

**Comment by potatoqualitee** [comment]
Booo that didnt work

**Comment by potatoqualitee** [comment]
Which file was that, @niphlod ?

**Comment by potatoqualitee** [comment]
found it!

**Comment by potatoqualitee** [comment]
yay, had to fix the output encoding  in find-dbacommand

![image](https://user-images.githubusercontent.com/8278033/178968402-24b16fcb-c17b-42d3-a0c6-f150e65afcfc.png)

**Comment by niphlod** [comment]
then it *should* work oob for the site

**Comment by potatoqualitee** [comment]
WAHOO! I reverted the change in the docs repo and just changed the find-dbacommand file and rebuilt the json to be in Unicode but the webpages remain in UTF8BOM

![image](https://user-images.githubusercontent.com/8278033/178969578-507b765e-e9a5-4499-9e18-e031d507bb53.png)

Gonna go add some metadata stuff now
