### ISSUE TITLE
Select-DbaObject documentation corrupted

### ISSUE THREAD

**Issue by jbelina** [dataplat/docs#67]
The synopsis, description, syntax and example sections appear to be corrupted in Select-DbaObject.html

**Comment by potatoqualitee** [comment]
It's true -- these are cmdlets and I'm not sure how to get them to show help. I need to remove them from the index

**Comment by jbelina** [comment]
Do these doc files get populated automatically?  If so, how does that work?

**Comment by potatoqualitee** [comment]
It's part of our [build process](https://github.com/potatoqualitee/release/blob/main/.github/workflows/dbatools.yml). The json file is built by executing `Find-DbaCommand -Rebuild`, then the website looks at the resulting JSON file and [parses through it to build the html files](https://github.com/dataplat/docs/blob/master/.github/workflows/update-assets.yml).
