### ISSUE TITLE
GitHub links are broken

### ISSUE THREAD

**Issue by wsmelton** [dataplat/docs#79]
Clicking on a handful of links to the code of a command takes me to the 404 page on GitHub.

I'm on my mobile doing this but not sure how that could matter.

**Comment by niphlod** [comment]
yep. I can definitely help, the structure of the repo changed. It was blob/master/functions/<fname>.ps1, is it okay if I change it to point to blob/master/public/<fname>.ps1 ? @potatoqualitee , @wsmelton
