### ISSUE TITLE
Copy-DbaLinkedServer error on SQL 2019

### ISSUE THREAD

**Issue by edwagner24** [dataplat/docs#81]
I am getting an error "The target principal name is incorrect" when trying to copy to SQL 2019 Server. I have always used just the server name when connecting.

**Comment by potatoqualitee** [comment]
Hey @edwagner24 -- this is the wrong repo. You will want https://github.com/dataplat/dbatools -- this is for the website. But to answer your question, check out https://dbatools.io/newdefaults
