### ISSUE TITLE
Find-DbaInstance -ScanType formatted incorrectly, missing each ScanType like seen in the help

### ISSUE THREAD

**Issue by wsuhoey** [dataplat/docs#87]
https://docs.dbatools.io/Find-DbaInstance

The ScanType formatting seems to be wrong, it is not showing what each scan type is doing, it's mangling them all together (see `docs example 1.png`)

<img width="717" alt="docs example 1" src="https://github.com/dataplat/docs/assets/28710553/37abd32b-110b-4b32-9d6d-b7b6db5b355a">

Contrast this with what's seen in the help (i.e. `Get-Help Find-DbaInstance -Full`) (see `docs example 2.png`)
<img width="814" alt="docs example 2" src="https://github.com/dataplat/docs/assets/28710553/5b581fd2-d30f-404b-b52e-2bae4f51c75b">

**Comment by niphlod** [comment]
whoops, completely lost this, I'll try and see what format helps better the doc page
