### ISSUE TITLE
New-DbaReplCreationScriptOptions - Examples show line break tags

### ISSUE THREAD

**Issue by DiHo78** [dataplat/docs#88]
The examples 1 and 2 for New-DbaReplCreationScriptOptions show the line break tag
See  [here ](https://docs.dbatools.io/New-DbaReplCreationScriptOptions)
![2024-03-26 10_54_38-dbatools docs _ New-DbaReplCreationScriptOptions](https://github.com/dataplat/docs/assets/27739194/71a5af1d-6890-4068-9119-dae0b0edc1f1)

**Comment by niphlod** [comment]
linked to https://github.com/dataplat/dbatools/pull/9292

**Comment by jpomfret** [comment]
This has been merged into the dev branch - next push to main we should be good
